document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title></title>");
document.writeln("<link href=\'css/js.css\' rel=\'stylesheet\' type=\'text/css\'>");
document.writeln("<script src=\'js/jquery1.js\' type=\'text/javascript\'></script>");
document.writeln("<script type=\'text/javascript\'>");
document.writeln("$(document).ready(function() {");
document.writeln("	  var blw=$(\'#myscrollbox li\').width();");
document.writeln("	  //获取单个子元素所需宽度");
document.writeln("	  var liArr = $(\'#myscrollbox ul\').children(\'li\');");
document.writeln("	  //获取子元素数量");
document.writeln("	  var mysw = $(\'#myscroll\').width();");
document.writeln("	  //获取子元素所在区域宽度");
document.writeln("	  var mus = parseInt(mysw/blw);");
document.writeln("	  //计算出需要显示的子元素的数量");
document.writeln("	  var length = liArr.length-mus;");
document.writeln("	  //计算子元素可移动次数（被隐藏的子元素数量）");
document.writeln("	  var i=0");
document.writeln("	  $(\'#right\').click(function(){");
document.writeln("		  i++");
document.writeln("		  //点击i加1");
document.writeln("		  if(i<length){");
document.writeln("		      $(\'#myscrollbox\').css(\'left\',-(blw*i));");
document.writeln("			  //子元素集合向左移动，距离为子元素的宽度乘以i。");
document.writeln("		  }else{");
document.writeln("			  i=length;");
document.writeln("			  $(\'#myscrollbox\').css(\'left\',-(blw*length));");
document.writeln("			  //超出可移动范围后点击不再移动。最后几个隐藏的元素显示时i数值固定位已经移走的子元素数量。");
document.writeln("	      }");
document.writeln("      });");
document.writeln("	  $(\'#left\').click(function(){");
document.writeln("		  i--");
document.writeln("		  //点击i减1");
document.writeln("		  if(i>=0){");
document.writeln("		     $(\'#myscrollbox\').css(\'left\',-(blw*i));");
document.writeln("			 //子元素集合向右移动，距离为子元素的宽度乘以i。");
document.writeln("		  }else{");
document.writeln("			 i=0;");
document.writeln("			 $(\'#myscrollbox\').css(\'left\',0);");
document.writeln("			 //超出可移动范围后点击不再移动。最前几个子元素被显示时i为0。");
document.writeln("	      }");
document.writeln("      });");
document.writeln("});");
document.writeln("</script>");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<div class=\'scrollpic\'>");
document.writeln("	<div id=\'mybtns\'> <a href=\'javascript:;\' id=\'right\'></a><a href=\'javascript:;\' id=\'left\'></a>  </div>");
document.writeln("	<div id=\'myscroll\'>");
document.writeln("		<div id=\'myscrollbox\'>");
document.writeln("			<ul>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (1).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140720</h5>");
document.writeln("							<!-- <p><img src=\'img/dh01 (2).jpg\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (3).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140720</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (4).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140606</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (4).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140631</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (4).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140542</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (5).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140720</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (6).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140631</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("				<li>");
document.writeln("					<a href=\'#\'>");
document.writeln("						<img src=\'img/dh01 (7).jpg\' width=\'260\' height=\'240\'>");
document.writeln("						<span class=\'intro\'>");
document.writeln("							<h5>P60305-140542</h5>");
document.writeln("							<!-- <p><img src=\'images/jia.png\' width=\'70\' height=\'70\' /></p> -->");
document.writeln("						</span>");
document.writeln("					</a>");
document.writeln("				</li>");
document.writeln("			</ul>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
document.writeln("    ");
document.writeln("</body>");
document.writeln("</html>");
document.writeln("");