document.writeln("<!DOCTYPE html PUBLIC \'-//W3C//DTD XHTML 1.0 Transitional//EN\' \'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\'>");
document.writeln("<html xmlns=\'http://www.w3.org/1999/xhtml\'>");
document.writeln("<head>");
document.writeln("<meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\' />");
document.writeln("<title></title>");
document.writeln("");
document.writeln("<link href=\'css/style.css\' type=\'text/css\' rel=\'stylesheet\' />");
document.writeln("<script type=\'text/javascript\' src=\'js/script.js\'></script>");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("<div id=\'ztbox\'>");
document.writeln("	<div id=\'left\'><</div>");
document.writeln("	<div id=\'conter\'>");
document.writeln("		<ul>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (1).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div>");
document.writeln("			</li>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (1).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div></li>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (2).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div></li>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (3).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div></li>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (4).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div></li>");
document.writeln("			<li><a href=\'#\'><img src=\'img/erhua01 (5).jpg\' /></a>");
document.writeln("			<div>欧米茄同轴·至臻天文台表45毫米</div></li>");
document.writeln("");
document.writeln("		</ul>");
document.writeln("		<div id=\'scroll\'><span></span></div>");
document.writeln("	</div>");
document.writeln("	<div id=\'right\'>></div>");
document.writeln("</div><!--ztbox end-->");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");